

const livros = [
  { id: 1, nome: "Gênesis", capitulos: 50 },
  { id: 2, nome: "Êxodo", capitulos: 40 },
  { id: 3, nome: "Levítico", capitulos: 27 },
  { id: 4, nome: "Números", capitulos: 36 },
  { id: 5, nome: "Deuteronômio", capitulos: 34 },
  { id: 6, nome: "Josué", capitulos: 24 },
  { id: 7, nome: "Juízes", capitulos: 21 },
  { id: 8, nome: "Rute", capitulos: 4 },
  { id: 9, nome: "1 Samuel", capitulos: 31 },
  { id: 10, nome: "2 Samuel", capitulos: 24 },
  { id: 11, nome: "1 Reis", capitulos: 22 },
  { id: 12, nome: "2 Reis", capitulos: 25 },
  { id: 13, nome: "1 Crônicas", capitulos: 29 },
  { id: 14, nome: "2 Crônicas", capitulos: 36 },
  { id: 15, nome: "Esdras", capitulos: 10 },
  { id: 16, nome: "Neemias", capitulos: 13 },
  { id: 17, nome: "Ester", capitulos: 10 },
  { id: 18, nome: "Jó", capitulos: 42 },
  { id: 19, nome: "Salmos", capitulos: 150 },
  { id: 20, nome: "Provérbios", capitulos: 31 },
  { id: 21, nome: "Eclesiastes", capitulos: 12 },
  { id: 22, nome: "Cantares", capitulos: 8 },
  { id: 23, nome: "Isaías", capitulos: 66 },
  { id: 24, nome: "Jeremias", capitulos: 52 },
  { id: 25, nome: "Lamentações", capitulos: 5 },
  { id: 26, nome: "Ezequiel", capitulos: 48 },
  { id: 27, nome: "Daniel", capitulos: 12 },
  { id: 28, nome: "Oseias", capitulos: 14 },
  { id: 29, nome: "Joel", capitulos: 3 },
  { id: 30, nome: "Amós", capitulos: 9 },
  { id: 31, nome: "Obadias", capitulos: 1 },
  { id: 32, nome: "Jonas", capitulos: 4 },
  { id: 33, nome: "Miqueias", capitulos: 7 },
  { id: 34, nome: "Naum", capitulos: 3 },
  { id: 35, nome: "Habacuque", capitulos: 3 },
  { id: 36, nome: "Sofonias", capitulos: 3 },
  { id: 37, nome: "Ageu", capitulos: 2 },
  { id: 38, nome: "Zacarias", capitulos: 14 },
  { id: 39, nome: "Malaquias", capitulos: 4 },
  { id: 40, nome: "Mateus", capitulos: 28 },
  { id: 41, nome: "Marcos", capitulos: 16 },
  { id: 42, nome: "Lucas", capitulos: 24 },
  { id: 43, nome: "João", capitulos: 21 },
  { id: 44, nome: "Atos", capitulos: 28 },
  { id: 45, nome: "Romanos", capitulos: 16 },
  { id: 46, nome: "1 Coríntios", capitulos: 16 },
  { id: 47, nome: "2 Coríntios", capitulos: 13 },
  { id: 48, nome: "Gálatas", capitulos: 6 },
  { id: 49, nome: "Efésios", capitulos: 6 },
  { id: 50, nome: "Filipenses", capitulos: 4 },
  { id: 51, nome: "Colossenses", capitulos: 4 },
  { id: 52, nome: "1 Tessalonicenses", capitulos: 5 },
  { id: 53, nome: "2 Tessalonicenses", capitulos: 3 },
  { id: 54, nome: "1 Timóteo", capitulos: 6 },
  { id: 55, nome: "2 Timóteo", capitulos: 4 },
  { id: 56, nome: "Tito", capitulos: 3 },
  { id: 57, nome: "Filemom", capitulos: 1 },
  { id: 58, nome: "Hebreus", capitulos: 13 },
  { id: 59, nome: "Tiago", capitulos: 5 },
  { id: 60, nome: "1 Pedro", capitulos: 5 },
  { id: 61, nome: "2 Pedro", capitulos: 3 },
  { id: 62, nome: "1 João", capitulos: 5 },
  { id: 63, nome: "2 João", capitulos: 1 },
  { id: 64, nome: "3 João", capitulos: 1 },
  { id: 65, nome: "Judas", capitulos: 1 },
  { id: 66, nome: "Apocalipse", capitulos: 22 }
];

export default livros;